/**
 * TypeScript interfaces for the ScamScrammer application
 */

// ============================================================================
// Twilio Webhook Payloads
// ============================================================================

/**
 * Payload received from Twilio when an incoming call arrives
 * @see https://www.twilio.com/docs/voice/twiml#request-parameters
 */
export interface TwilioWebhookPayload {
  /** A unique identifier for this call, generated by Twilio */
  CallSid: string;
  /** Your Twilio Account SID */
  AccountSid: string;
  /** The phone number of the caller */
  From: string;
  /** Your Twilio phone number that received the call */
  To: string;
  /** The status of the call */
  CallStatus: 'queued' | 'ringing' | 'in-progress' | 'completed' | 'busy' | 'failed' | 'no-answer' | 'canceled';
  /** The version of the Twilio API used */
  ApiVersion: string;
  /** The direction of the call */
  Direction: 'inbound' | 'outbound-api' | 'outbound-dial';
  /** The forwarding phone number, if any */
  ForwardedFrom?: string;
  /** Geographic data for the From phone number */
  CallerName?: string;
  FromCity?: string;
  FromState?: string;
  FromZip?: string;
  FromCountry?: string;
  /** Geographic data for the To phone number */
  ToCity?: string;
  ToState?: string;
  ToZip?: string;
  ToCountry?: string;
  /** Parent call SID if this is a child call */
  ParentCallSid?: string;
}

/**
 * Payload received from Twilio for call status callbacks
 * @see https://www.twilio.com/docs/voice/api/call-resource#statuscallback
 */
export interface TwilioStatusPayload {
  /** A unique identifier for this call */
  CallSid: string;
  /** Your Twilio Account SID */
  AccountSid: string;
  /** The phone number of the caller */
  From: string;
  /** Your Twilio phone number */
  To: string;
  /** The current status of the call */
  CallStatus: 'initiated' | 'ringing' | 'answered' | 'completed' | 'busy' | 'failed' | 'no-answer' | 'canceled';
  /** The direction of the call */
  Direction: 'inbound' | 'outbound-api' | 'outbound-dial';
  /** Duration of the call in seconds (only present when completed) */
  CallDuration?: string;
  /** Timestamp when the call started */
  Timestamp?: string;
  /** Sequence number of this status callback */
  SequenceNumber?: string;
  /** The duration of the call in seconds */
  Duration?: string;
}

/**
 * Payload received from Twilio when a recording is completed
 * @see https://www.twilio.com/docs/voice/api/recording#statuscallback
 */
export interface TwilioRecordingPayload {
  /** Your Twilio Account SID */
  AccountSid: string;
  /** The SID of the call that was recorded */
  CallSid: string;
  /** The unique SID of this recording */
  RecordingSid: string;
  /** The URL where the recording can be accessed */
  RecordingUrl: string;
  /** The status of the recording */
  RecordingStatus: 'in-progress' | 'completed' | 'absent' | 'failed';
  /** The duration of the recording in seconds */
  RecordingDuration?: string;
  /** The number of channels in the recording */
  RecordingChannels?: string;
  /** The source of the recording */
  RecordingSource?: string;
  /** Error code if recording failed */
  ErrorCode?: string;
}

// ============================================================================
// Call Enums and Types
// ============================================================================

/**
 * Status of a call in our system
 */
export enum CallStatus {
  RINGING = 'RINGING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NO_ANSWER = 'NO_ANSWER',
}

/**
 * Speaker identification in conversation segments
 */
export enum Speaker {
  SCAMMER = 'SCAMMER',
  EARL = 'EARL',
}

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Call record as returned by the API
 */
export interface CallResponse {
  id: string;
  twilioSid: string;
  fromNumber: string;
  toNumber: string;
  status: CallStatus;
  duration: number | null;
  recordingUrl: string | null;
  transcriptUrl: string | null;
  rating: number | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  segments?: CallSegmentResponse[];
}

/**
 * Call segment (part of conversation) as returned by the API
 */
export interface CallSegmentResponse {
  id: string;
  callId: string;
  speaker: Speaker;
  text: string;
  timestamp: number;
  createdAt: string;
}

// ============================================================================
// OpenAI Realtime Types
// ============================================================================

/**
 * Configuration for OpenAI Realtime API sessions
 */
export interface OpenAIRealtimeConfig {
  /** The model to use (e.g., "gpt-4o-realtime-preview") */
  model: string;
  /** Voice to use for responses */
  voice: 'alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer';
  /** System prompt for the AI */
  systemPrompt: string;
  /** Temperature for response generation (0-2) */
  temperature?: number;
  /** Maximum tokens in response */
  maxTokens?: number;
  /** Audio format configuration */
  inputAudioFormat?: 'pcm16' | 'g711_ulaw' | 'g711_alaw';
  outputAudioFormat?: 'pcm16' | 'g711_ulaw' | 'g711_alaw';
  /** Turn detection settings */
  turnDetection?: {
    type: 'server_vad';
    threshold?: number;
    prefix_padding_ms?: number;
    silence_duration_ms?: number;
  };
}

// ============================================================================
// Earl Persona Types
// ============================================================================

/**
 * Configuration for the Earl AI persona
 */
export interface EarlPersonaConfig {
  name: string;
  age: number;
  background: string;
  personality: string[];
  tangentTopics: string[];
  signaturePhrases: string[];
  mishearings: Record<string, string>;
  responseDelayMs: {
    min: number;
    max: number;
  };
}

// ============================================================================
// Dashboard Types
// ============================================================================

/**
 * Statistics for the dashboard
 */
export interface DashboardStats {
  totalCalls: number;
  totalDuration: number;
  averageDuration: number;
  callsByStatus: Record<CallStatus, number>;
  callsByDay: Array<{
    date: string;
    count: number;
  }>;
  topRatedCalls: CallResponse[];
  longestCalls: CallResponse[];
}

/**
 * Pagination options for list queries
 */
export interface PaginationOptions {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// ============================================================================
// Twilio Client Types
// ============================================================================

/**
 * Options for generating TwiML responses
 */
export interface TwiMLOptions {
  /** Voice to use for Say verb */
  voice?: 'alice' | 'man' | 'woman' | 'Polly.Matthew' | 'Polly.Joanna';
  /** Language for the voice */
  language?: string;
  /** Whether to record the call */
  record?: boolean;
  /** Callback URL for recording status */
  recordingStatusCallback?: string;
}

/**
 * Call details returned from Twilio API
 */
export interface TwilioCallDetails {
  sid: string;
  status: string;
  from: string;
  to: string;
  direction: string;
  duration: number | null;
  startTime: Date | null;
  endTime: Date | null;
  price: string | null;
  priceUnit: string | null;
}

/**
 * Recording details returned from Twilio API
 */
export interface TwilioRecordingDetails {
  sid: string;
  callSid: string;
  status: string;
  duration: number;
  url: string;
  mediaUrl: string;
}
